### ISSUE TITLE
Some department names are cut off, all caps

### ISSUE THREAD

**Issue by alex-engelmann** [openoakland/openousd-site#19]
In the main departments table, a few of the departments have wonky names:

"Comm. Schools & Student Servic" probably Services?

"Human Resources Services, Supp" not sure what this is supposed to be

"Eng Lang Lrnr/Multilingual Ach"

LINKED LEARNING is in all caps for some reason.  

These need to be fixed on the database or in the query, as they're dynamically generated. Otherwise I'd edit them myself :)

**Comment by jbaldo** [comment]
fixed with #27
